class EpayService

  ERROR_CODES = { '-10006' => "The user canceled the EWIRE transaction",
                  '-5604'  => "Fee can not be calculated for the card type used.",
                  '-5603'  => "The store does not allow the type of card.",
                  '-5602'  => "An invalid currency code has been used.",
                  '-5601'  => "Fee can not be calculated for the card type used.",
                  '-5600'  => "The card number is not accurate - invalid prefix (must be 6 characters).",
                  '-5516'  => "The payment window was closed by user.",
                  '-5514'  => "Customer's session has either expired or the payment process has not started correctly.",
                  '-5511'  => "An error has occurred! Please restart the payment process.",
                  '-5509'  => "You get the error Not valid data when you try to open the Standard Payment window. You get this error because ePay can not find the data to the transaction. This error occurs because the user / client has been inactive for more than 20 minutes!",
                  '-5508'  => "You receive the rror \"No valid domains created for the company\", when you try to open the payment window. You receive this error as you have not entered the domain for your account in the payment system. In the payment system in the menu \"Settings\" and \"Payment system\" you can see the domain(s) assigned to your accout.",
                  '-5507'  => "You receive the error \"URL not allowed for relaying\", when you try to open the payment window. You receive this error as the domain you open up the window from, is not entered in the payment system. In the administration to the payment system from the menu \"Settings\" and \"Payment System\", you can enter you domain.",
                  '-5506'  => "You get the error Invalid merchant number, when you try to open the Standard Payment window. You get this error because it indløsningsnummer / merchant number you use is not established in the payment! Check whether you are using the correct merchant number.",
                  '-5505'  => "You get the error No cardtypes defined when you try to open the Standard Payment window. This is because there are NO cards up to your account in the payment system.",
                  '-5504'  => "You get the error Invalid currencycode when you try to open the Standard Payment window. You get this error because you are using an invalid currencycode. You can from your administration to thepayment system in the menu \"Support\" and \"Currency Codes\" see the list of currency codes available.",
                  '-5503'  => "The data that you send to the payment window are not correct! You get a description of the data as it is not listed correctly.",
                  '-5502'  => "You receive the error \"Invalid company\" when you try to open the payment window. You receive this error as you have not activated the payment window yet. You have to activate the window from your administration to the payment system from the menu \"Settings\" and \"Payment window\".",
                  '-5501'  => "You receive the error \"Window not activated\", when you try to open the payment window. You receive this error as you have not activated the payment window yet. You have to activate the window from your administration to the payment system from the menu \"Settings\" and \"Payment window\".",
                  '-2003'  => "Declined - Issuers country / region does not match the country the payment come from.",
                  '-2002'  => "Declined - Nonsecure payments from country / region are not accepted.",
                  '-2001'  => "Declined - Payments from country / region are not accepted.",
                  '-2000'  => "Declined - Payments from your IP Address are not accepted.",
                  '-1602'  => "PBS test gateway is unfortunately down at the moment, please try again later.",
                  '-1601'  => "The reply sent to the payment system was expected to be from a bank, but is invalid. Invalid data was posted.",
                  '-1600'  => "The session of banking has already been used. The same session can not be used again.",
                  '-1303'  => "Rejected - Payment could not be increased - rejected by EWIRE.",
                  '-1302'  => "Rejected - Error ewire MD5 data. Check the MD5 data is posted in both EWIRE and ePay.",
                  '-1301'  => "Rejected - EWIRE emrchant number was not found - Check if your EWIRE merchant number is setup at ePay.",
                  '-1300'  => "You tried to pay with a credit card which is not accepted by the merchant. Please try another credit card or contact the merchant.",
                  '-1200'  => "Unknown currency code. You can only use the currency codes that you can see in the menu \"Support\" and \"Currency Codes\" in the administration.",
                  '-1100'  => "Invalid data received at the payment system. You must remember to send the amount in the smallest unit / minor units (eg GBP must. Specified in Pennies), and may not use the comma or dot (separator). Please also remember to send the fields cardno, expmonth and expyear which are also mandatory.",
                  '-1024'  => "Invalid card number entered. Please correct and try again.",
                  '-1023'  => "The transaction is already captured",
                  '-1022'  => "The transaction is declined as the merchant blocks all transactions made by the matching card number.",
                  '-1021'  => "An operation every 15 minutes can be performed on a transaction. Please wait 15 minutes and try again.",
                  '-1020'  => "The transaction is deleted",
                  '-1019'  => "Invalid password used for webservice access!",
                  '-1018'  => "Invalid test-card used! You find the correct test-information from the menu Support - Test Information as you are logged into the payment system.",
                  '-1017'  => "No access to PCI required function!",
                  '-1016'  => "There is disruption at the acquirer. This is an offline procedure. Please wait a moment and try again.",
                  '-1015'  => "Currency code was not found. You should check your currency code you can accept payments with.",
                  '-1014'  => "The transaction could not be made as 3D secure. The transaction is declined. Try another credit card or contact the merchant.",
                  '-1012'  => "Rejected - Unable to renew this type of card.",
                  '-1011'  => "MD5 stamp was not valid.",
                  '-1010'  => "The cardtype was not found in the specified list of predefined card types (field cardtype). If you wish to receive this type of card you need to add the card type to this list.",
                  '-1009'  => "Subscription was not found.",
                  '-1008'  => "The transaction could not be found.",
                  '-1007'  => "There are differences in the amount captured / available. Please examine the amount of which is captured / credited against the amount authorized / captured. Note if there is a Euroline transaction and the transaction is captured, it can only be credited the following day.",
                  '-1006'  => "Product Unavailable.",
                  '-1005'  => "Disruption - try again later.",
                  '-1004'  => "Error code not found.",
                  '-1003'  => "No access to the ipaddress for remote interface (API).",
                  '-1002'  => "Merchantnumber was not found in the payment system.",
                  '-1001'  => "Order number already exists.",
                  '-1000'  => "Communication disorders at the acquirer.",
                  '-23'    =>  "PBS test gateway unavailable.",
                  '-4'     =>  "Communication disorders at the acquirer.",
                  '-3'     =>  "Communication disorders at the acquirer.",
                  '4000'   => "eDankort / PBS 3D secure / Banking - payment interrupted by user",
                  '4001'   => "SOLO - user cut off payment",
                  '4002'   => "SOLO - the user was rejected",
                  '4003'   => "SOLO - errors in MAC (MD5)",
                  '4100'   => "Rejected - No answer",
                  '4101'   => "Rejected - Call the card issuer",
                  '4102'   => "Rejected - Call the card issuer and keep the card (fraud)",
                  '4103'   => "The payment was declined. You might have entered wrong information. Please try again or contact the merchant.",
                  '4104'   => "Rejected - System Error - no answer",
                  '4105'   => "Rejected - unknown error",
                  '4106'   => "Rejected - Card is not approved by VISA / MasterCard / JCB (3D Secure). Please try again.",
                  '4107'   => "Rejected - Can not release Euro Line (SEB) payment (not supported)",
                  '4108'   => "Rejected - Can not renew Euro Line (SEB) payment (not supported)",
                  '4109'   => "Rejected - card could not be approved by the 3D secure",
                  '4110'   => "Rejected - An error occurred during the approval of 3D secure",
                  '4111'   => "Rejected - The card could not be found in 3D secure",
                  '10004'  => "The payment via Danske Bank was aborted.",
                  '10005'  => "The payment via Danske Bank was aborted.",

                   '-1013' => "Your payment was declined. Please try again.",
                   '-2' => "Communication disorders at the acquirer.",
                   '-1' => "Communication disorders at the acquirer.",
                   '0' => "Approved",
                   '1' => "Declined - Call issuer",
                   '2' => "Declined - Call issuer",
                   '3' => "Declined - invalid merchant number",
                   '4' => "Declined - Call issuer",
                   '5' => "Declined – The card issuing bank declined the transaction.",
                   '6' => "Declined - Unable to process transaction",
                   '7' => "Declined - Call Issuer",
                   '12' => "Declined - Invad transaction - eg serviec not permitted to card type",
                   '13' => "Declined - Invalid amount",
                   '14' => "Declined - Invalid card number",
                   '15' => "Declined - Unable to determine issuer",
                   '30' => "Declined - Format error",
                   '33' => "Declined - Expired card",
                   '41' => "Declined - Call issuer",
                   '43' => "Declined - Call issuer",
                   '51' => "Declined - Insufficient funds",
                   '54' => "Declined - Expired card",
                   '57' => "Declined - Transaction not permitted to cardholder",
                   '61' => "Declined - Activity amount limit exceeded",
                   '62' => "Declined - restricted card",
                   '65' => "Declined - Activity amount limit exceeded",
                   '75' => "The card is blocked / locked",
                   '83' => "Declined - invalid card number - try again",
                   '88' => "Declined - invalid card number - try again",
                   '100' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '101' => "The payment was declined as the credit card is expired. Please try with another credit card.",
                   '102' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '103' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '104' => "The payment was declined as the credit card can only be used in the card holder home country. Try with another credit card.",
                   '105' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '106' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '107' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '108' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '109' => "The payment was declined as the merchant has not an agreement to the credit card used for this transaction. Try with another credit card.",
                   '110' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '111' => "The payment was declined as the credit card number can not be found. Try to enter the credit card information again or try with another credit card.",
                   '112' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '113' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '114' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '115' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '116' => "The payment was declined as there is no coverage of the transaction amount. Try with another credit card.",
                   '117' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '118' => "The payment was declined as the credit card number can not be found. Try to enter the credit card information again or try with another credit card.",
                   '119' => "The payment was declined as there is no coverage of the transaction amount. Try with another credit card.",
                   '120' => "The payment was declined as the merchant has not an agreement to the credit card used for this transaction. Try with another credit card.",
                   '121' => "The payment was declined as there is no coverage of the transaction amount. Try with another credit card.",
                   '122' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '123' => "The payment was declined as there is no coverage of the transaction amount. Try with another credit card.",
                   '124' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '125' => "The payment was declined as the credit card is expired. Please try with another credit card.",
                   '126' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '127' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '128' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '129' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '160' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '161' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '162' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '164' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '165' => "Declined. The card number entered had an incorrect length. Please check if you have entered the information correctly and try again.",
                   '167' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '173' => "The payment was declined as the credit card number can not be found. Try to enter the credit card information again or try with another credit card.",
                   '200' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '201' => "The payment was declined as the credit card number can not be found. Try to enter the credit card information again or try with another credit card.",
                   '202' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '203' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '204' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '205' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '206' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '207' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '208' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '209' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '210' => "The payment was declined of unknown reasons. For more information contact the bank. E.g. try with another credit card. Denied - Call your bank for information",
                   '900' => "Approved",
                   '901' => "Approved",
                   '902' => "The payment was declined as the credit card number can not be found. Try to enter the credit card information again or try with another credit card.",
                   '903' => "The payment was declined. Try again in a moment or try with another credit card.",
                   '904' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '905' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '906' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '907' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '908' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '909' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '910' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '911' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '912' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '913' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '914' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '915' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '916' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '917' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '918' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '919' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '920' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '921' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '922' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '923' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '940' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '945' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '946' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '950' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '984' => "The payment was declined - system errror / timeout. Wait a moment and try again with the current or another credit card.",
                   '999' => "Declnied - Reason could not be determined",
                   '1315' => "Declined - PayPal is not setup to this account - please select another payment method",
                   '5001' => "Unknown account",
                   '5002' => "Unknown account",
                   '5003' => "Specified amount exceeds the Paii system limits",
                   '5005' => "Authorization timed out as user did not enter a PIN",
                   '5006' => "Capture failed because the authorization timed-out",
                   '5007' => "Transaction is already captured",
                   '5008' => "PIN declined by user",
                   '10006' => "Canceled at EWIRE",
                   '50011' => "Refund failed because transaction is already completely refunded",
                   '50012' => "Refund failed because the transaction has exceeded the limit it can be refunded",
                   '50013' => "Transaction cannot be canceled. Transaction is in wrong state or timed out.",
                   '50014' => "Capture is not allowed on a failed transaction",
                   '50015' => "Transaction cannot be refunded because of it is not captured",
                   '50020' => "Shortcode not allowed",
                   '50021' => "Shortcode purchase limit violation",
                   '50022' => "Content category purchase limit violation",
                   '50023' => "Content category not allowed",
                   '50024' => "Specified amouint failed due to error at acquirer",
                   '50025' => "Auto top up is not enabled",
                   '50026' => "Payment card not valid or expired",
                   '50027' => "Specified amount exceeds the Paii wallet account limit" }

  def initialize ecp, params = {}
    @ecp = ecp
    @store = @ecp.event.store
    @company = @store.company
    @params = params
  end

  def purchase
    prepare_epay
    begin
      transaction = Epay::Transaction.create(
        card_no:   @params[:card_number],
        exp_year:  @params[:card_expires_year]['date(1i)'],
        exp_month: @params[:card_expires_month]['date(2i)'],
        cvc:       @params[:cvc],
        amount:    @ecp.price.to_i,
        order_no:  "Order ##{ @ecp.id }",
        group:     'Online Booking',
        cardholder: @ecp.customer.full_name,
        description: @ecp.event.name
      )
    rescue Exception => e
      transaction = {}
      transaction[:error] = e.message
    end

    return transaction if transaction.kind_of?(Hash)
    return { error: ERROR_CODES[transaction.error].blank? ? transaction.error : ERROR_CODES[transaction.error]} if transaction.kind_of?(Epay::Transaction) && !transaction.success?
    transaction
  end

  private
  def prepare_epay
    Epay.merchant_number = @company.payment_credential.epay_merchant_number.to_i
    Epay.password = @company.payment_credential.epay_password
    Epay.default_currency = @company.payment_credential.epay_currency.to_sym
  end
end
