source 'http://rubygems.org'
#ruby '2.2.4'

gem 'rails', '~> 3.2.22'

gem 'aasm'
gem 'activeadmin', github: 'activeadmin', branch: '0-6-stable'
gem 'activemerchant', require: 'active_merchant'
gem 'acts_as_paranoid'
gem 'acts-as-taggable-on'
gem 'airbrake'
gem 'apipie-rails'
gem 'barby', github: 'kaktusyaka/barby'
gem 'best_in_place'
gem 'bootbox-rails'
gem 'bootstrap-datepicker-rails'
gem 'cancan'
gem 'client_side_validations', github: 'bcardarella/client_side_validations', branch: '3-2-stable'
gem 'client_side_validations-simple_form'
gem 'coffee-rails'
gem 'combined_time_select', '~> 1.0.1'
gem 'country_select'
gem 'datejs-rails', github: 'oceanshq/datejs-rails'
gem 'delayed_job_active_record'
gem 'delayed-plugins-airbrake'
gem 'deep_cloneable', '~> 2.0.0'
gem 'devise'
gem 'draper', '~> 1.0'
gem 'dygraphs-rails'
gem 'dynamic_form', github: 'kaktusyaka/dynamic_form'
gem 'easy_as_pie'
gem 'email_veracity', github: 'kaktusyaka/email-veracity'
gem 'epay'
gem 'figaro'
gem 'fullcalendar-rails'
gem 'gibbon'
gem 'gon'
gem 'haml'
gem 'i18n-js'
gem 'inherited_resources'
gem 'jquery-cookie-rails', github: 'akradev/jquery-cookie-rails'
gem 'jquery-rails', '2.3.0'
gem 'jquery-slimscroll-rails'
gem 'jquery-tmpl-rails'
gem 'jquery-ui-rails'
gem 'json2-rails'
gem 'js-routes'
gem 'kaminari-bootstrap', '~> 0.1.3'
gem 'kaminari-i18n'
gem 'modernizr-rails'
gem 'nested_form', github: 'ryanb/nested_form'
gem 'paper_trail', '~> 3.0.6'
gem 'paperclip', '3.5.2'
gem 'pg'
gem 'pg_search'
gem 'prettyphoto-rails'
gem 'puma'
gem 'qif'
gem 'rabl-rails'
gem 'rack-attack'
gem 'rails-bootstrap-toggle-buttons'
gem 'rails-jasny-bootstrap-extension', github: 'kaktusyaka/rails-jasny-bootstrap-extension'
gem 'ransack'
gem 'sass-rails'
gem 'select2-rails'
gem 'simple_form'
gem 'squeel', '1.0.18'
gem 'stripe', '~> 1.8.4', github: 'stripe/stripe-ruby'
gem 'test-unit', '~> 3.0', require: false
gem 'time_diff'
gem 'twitter-bootstrap-rails'
gem 'touchpunch-rails'
gem 'turnout'
gem 'turbo-sprockets-rails3'
gem 'uglifier', '>= 1.0.3'
gem 'unscoped_associations'
gem 'validates_email_format_of', github: 'alexdunae/validates_email_format_of'
gem "validates_existence", github: 'perfectline/validates_existence'
gem 'validates_timeliness'
gem 'validate_url'
gem 'xeroizer', github: 'waynerobinson/xeroizer'
gem 'enumerize'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'roo'
gem 'roo-xls'
gem 'faraday'
gem 'faraday_middleware'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'rack-mini-profiler', require: false
  gem 'clear_migrations'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 2.6.1'
  gem 'simplecov', require: false
  gem 'rspec-retry'
end

group :test, :development do
  gem 'factory_girl_rails', '~> 4.0'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails', '2.99.0'
end
